export const SENTENCES_STACK_FOR_GRAMMAR = [
	'Big data is being analyzed in real time to predict customer behavior.',
	'Augmented-reality headsets have been adopted by several hospitals to train surgeons.',
	'Will quantum computing be embraced by mainstream businesses within the decade?',
	'These constant pop-up ads aren’t annoying, are they?',
	'Moreover, video conferencing, which facilitates remote collaboration, is reshaping office culture.',
	'In my opinion, the Internet of Things will revolutionize urban planning.',
	'Participating in the debate, she argued that social-media platforms must be regulated.',
	'Streaming services are being preferred over traditional broadcasting worldwide.',
	'Nevertheless, cyber-security remains a pressing concern; furthermore, data breaches damage trust.',
	'Isn’t it true that e-mail has become less popular among teenagers?',
	'Cloud computing has been heralded as the backbone of digital transformation.',
	'By 2030, remote workspaces will be managed entirely through virtual-reality dashboards.',
	'Applicants fluent in Python, possessing AWS certification, and boasting machine-learning experience stand out immediately.',
	'My colleague, who is undeniably visionary, suggested prototyping early to identify flaws.',
	'To solve connectivity issues, one practical solution is installing a mesh network.',
	'Employees motivated by curiosity often generate breakthrough ideas.',
	'Lack of feedback, analyzed carefully, shows why the project stalled.',
	'Her résumé, which was meticulously formatted, highlighted transferable skills.',
	'Designers known for their adaptability frequently pivot during development.',
	'Frankly, the fact remains: our cost-benefit ratio favors automation.',
	'When bandwidth drops, rebooting the router is a quick fix.',
	'The prototype, tested repeatedly, proved viable.',
	'Innovative thinkers, who thrive under pressure, often cultivate a culture of experimentation.',
	'Root-cause analysis revealed that inadequate training led to errors.',
	'While residents of Quito greet with a handshake, people from Tokyo bow politely.',
	'Back then, our family gathered around a radio during the evenings, but now everyone streams podcasts individually.',
	'Some professionals stay calm under stress, whereas others keep complaining about minor issues.',
	'Generally speaking, community-oriented cultures place a higher value on collective success.',
	'Except for a few regional differences, holiday traditions remain remarkably similar across the country.',
	'He always brought home-made desserts to meetings while employed here.',
	'Tourists keep asking for eco-friendly options, so hotels stay competitive by adopting green policies.',
	'On the other hand, city dwellers dine out frequently, whereas rural families cook at home.',
	'Accepting change is difficult; nevertheless, many employees embrace automation.',
	'Years ago, our group wrote postcards and waited weeks for a reply.',
	'Although smartphones simplify communication, they also keep users constantly distracted.',
	'By and large, people prefer flexible schedules over rigid nine-to-five routines.',
	'Slow-loading webpages drive me crazy during rush hours.',
	'I get irritated when automated voices mispronounce my name.',
	'Long queues at the bank make me feel exhausted.',
	'Could you tell me why the printer keeps jamming every morning?',
	'The colleague who never replies to emails is my biggest source of frustration.',
	'What bothers her most is that meetings start late.',
	'If customers feel annoyed, sending a quick apology email may avoid further problems.',
	'He politely suggested that we double-check the cables before calling support.',
	'Did that issue get resolved following the update, or does it still cause errors?',
	'Broken coffee machines, outdated keyboards, and flickering monitors were mentioned in the complaint list.',
	'Our supervisor, who is typically even-tempered, sounded disappointed during today’s briefing.',
	'Could you tell me where to submit a formal request for quieter workspaces?',
	'The constant notifications are getting on everyone’s nerves, so silent mode was activated.',
	'Satisfied and relieved, our team celebrated after the bug had been fixed.',
];
